apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi-prod
  template:
    metadata:
      labels:
        app: webapi-prod
    spec:
      containers:
      - name: webapi
        image: myapp:latest
        ports:
        - containerPort: 8082  # Use a different internal port for development
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-prod
spec:
  selector:
    app: webapi-prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082  # Map external port 80 to the internal port 8081
  type: NodePort

